### ISSUE TITLE
数据集配置问题--seg测试过程

### ISSUE THREAD

**Issue by fak111** [Linfeng-Tang/PSFusion#16]
作者你给的MFnet数据集链接下载后解压是
![image](https://github.com/Linfeng-Tang/PSFusion/assets/97438502/d35e09c6-bdc4-499c-b4a8-4816c7a86e10)

但我看您发的参考博客  要求是voc格式 我改成voc后仍出现问题
![image](https://github.com/Linfeng-Tang/PSFusion/assets/97438502/c7de1513-cafe-4627-b1d6-54d2ab345dec)
/data/miniconda/envs/seg/bin/python3.7 /data/PSFusion-SegNeXt/tools/test.py --aug-test 
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
/data/miniconda/envs/seg/lib/python3.7/site-packages/mmengine/model/utils.py:137: UserWarning: Cannot import torch.fx, `merge_dict` is a simple function to merge multiple dicts
  warnings.warn('Cannot import torch.fx, `merge_dict` is a simple function '
2024-06-20 22:50:18,525 - mmseg - INFO - Loaded 242 images
Traceback (most recent call last):
  File "/data/miniconda/envs/seg/lib/python3.7/site-packages/mmcv/utils/registry.py", line 179, in build_from_cfg
    return obj_cls(**args)
  File "/data/PSFusion-SegNeXt/mmseg/datasets/voc.py", line 29, in __init__
    assert osp.exists(self.img_dir) and self.split is not None
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/PSFusion-SegNeXt/tools/test.py", line 341, in <module>
    main()
  File "/data/PSFusion-SegNeXt/tools/test.py", line 206, in main
    dataset = build_dataset(cfg.data.test)
  File "/data/PSFusion-SegNeXt/mmseg/datasets/builder.py", line 73, in build_dataset
    dataset = build_from_cfg(cfg, DATASETS, default_args)
  File "/data/miniconda/envs/seg/lib/python3.7/site-packages/mmcv/utils/registry.py", line 182, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
AssertionError: PascalVOCDataset: 
按照您给的步骤我无法进行测试，本人太菜作者大大可不可以写详细点 
![image](https://github.com/Linfeng-Tang/PSFusion/assets/97438502/f51ca31c-1973-4050-b7da-67e6dd9cba82)

**Comment by Linfeng-Tang** [comment]
这应该是dataloader没有整好的原因呢 你可以根据代码再重新设置一下代码目录
